feat: add moehu support
koishijs/koishi-plugin-booru pull request #56
Opened 2023-03-30 09:28 UTC by Kabuda-czh

2023-03-30 09:29 UTC, Kabuda-czh commented
python script
```python
import requests
import re
from bs4 import BeautifulSoup

"""
    2023.3.30 版本
"""

res = requests.get("https://img.moehu.org/")
bs = BeautifulSoup(res.text, 'html.parser')

menu_divs = bs.find_all(class_='menuDiv')[:-3]

# 最终返回的 json 数据
key_map = {}

for menu in menu_divs:
    menu_ul = menu.find_next('ul')
    for pre in menu_ul.find_all('pre'):
        name, id_ = re.search(r'\((.*?)→.*id=(.*?)".*?>', str(pre)).groups()
        key_map[name] = id_

```

2023-11-30 09:10 UTC, Kabuda-czh reviewed
review

2024-03-15 15:08 UTC, Lipraty commented on packages/moehu/src/index.ts
> +    const { data } = await this.ctx.http.axios<Moehu.Response>(url)
migrate legacy `.axios()` to `.get()`

2024-03-15 15:09 UTC, Lipraty reviewed
upgrade dependencies

2024-03-16 15:43 UTC, Lipraty requested changes

2024-03-16 15:43 UTC, Lipraty commented on packages/moehu/src/index.ts
> +  languages = ['en']
```suggestion
  languages = ['en', 'zh']
```

2024-03-16 16:06 UTC, Lipraty approved these changes

2024-03-17 04:36 UTC, merged